# Generated by Django 4.2.3 on 2023-07-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='high_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.ManyToManyField(blank=True, to='todo.tag'),
        ),
    ]
