# Generated by Django 4.2.3 on 2023-07-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_status_alter_todo_high_priority_alter_todo_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tag',
            new_name='tags',
        ),
    ]
